---
services:
  postgres:
    container_name: pgport-postgres
    image: postgres:15
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pgport
      POSTGRES_PASSWORD: pgport
      POSTGRES_USER: pgport
    healthcheck:
      test: pg_isready -U pgport -h 127.0.0.1
      interval: 5s
    networks:
      - pgport

  pgport:
    container_name: pgport
    image: mohamedelhefni/pgport:latest
    build: .
    environment:
      pgport_DATABASE_URL: postgres://pgport:pgport@pgport-postgres:5432/pgport?sslmode=disable
    ports:
      - 8081:8081
    networks:
      - pgport
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s

volumes:
  data:
    name: pgport_postgres

networks:
  pgport:
    name: pgport
