name: docker

on:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  DOCKER_REPOSITORY: mohamedelhefni/pgport
  GHCR_REPOSITORY: mohamedelhefni/pgport

jobs:
  docker-build:
    name: Build docker images
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configure docker build context
        uses: docker/setup-buildx-action@v2

      - name: Build docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ env.DOCKER_REPOSITORY }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7

  docker-release:
    name: Push docker images
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configure docker build context
        uses: docker/setup-buildx-action@v2

      - name: Set reference tags
        id: refs
        run: |
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPOSITORY }}:${{ steps.refs.outputs.SOURCE_TAG }}
            ${{ env.DOCKER_REPOSITORY }}:latest
            ghcr.io/${{ env.GHCR_REPOSITORY }}:${{ steps.refs.outputs.SOURCE_TAG }}
            ghcr.io/${{ env.GHCR_REPOSITORY }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
